name: cfn-github-actions
on:
  pull_request:
    branches:
    - main
jobs:
  check-cfn:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install CFN tools
        run: |
          gem install cfn-nag
      - name: CFN Nag scan
        run: |
          cfn_nag_scan --input-path  01-mgmt_account_setup_stack.yaml
      - name: Install cfn-lint
        run: |
          pip install cfn-lint
      - name: CFN Lint
        run: |
          cfn-lint 01-mgmt_account_setup_stack.yaml
      - name: CFN Nag scan1
        run: |
          cfn_nag_scan --input-path  02-account-tag-association-stackset.yaml
      - name: CFN Lint1
        run: |
          cfn-lint 02-account-tag-association-stackset.yaml
